apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: go-api-server
spec:
  tag: ${HARBOR_SVC}:8085/library/build-service/go-api-server
  serviceAccount: default
  builder:
    kind: ClusterBuilder
    name: default
  source:
    git:
      url: https://github.com/garreeoke/tap-go
      revision: main