mirrors:
  harbor.external.ip:8085:
    endpoint:
      - "http://harbor.external.ip:8085"
configs:
  "harbor.external.ip:8085":
    auth:
      username: admin # this is the registry username
      password: Harbor12345 # this is the registry password